name: ℹ️ 询问信息
description: 帮助您更加了解数据包机制
title: "[Inquiry] 标题"
assignees: wen-wen520
labels:
  - "ℹ️ Inquiry"
body:      
- type: markdown
  attributes: 
    value: |
      或许 Discussion 更好？

- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: 描述
     description: 请简短的描述你想要了解什么信息
